### ISSUE TITLE
Date on "working on" page rendered in UTC format

### ISSUE THREAD

**Issue by jwbrunt** [PASTAplus/dashboard#8]
All the other pages seem to display MST except for 

https://dashboard.edirepository.org/dashboard/pasta/render_working_on

![https-dashboard-edirepository-org-dashboard-pasta-render_working_on](https://user-images.githubusercontent.com/12550652/100951542-fb0ef900-34cb-11eb-9fb0-0a9fd45cda78.png)

**Comment by servilla** [comment]
Feexit, please

---
Mark Servilla
mark.servilla@gmail.com

**Comment by servilla** [comment]
The `PASTA is Working On` web page was correct set to display MT timezone, but the `PASTA Reserved Identifiers` was still displayling UTC. This issue (specifically for `PASTA Reserved Identifiers`) is now fixed with commit 3fdccb15c1d62c3994f6ff07170e8bc1c5846535.
